// Generated by rotor; do not edit. This file is refreshed automatically.
// Editor types for rotor's compile-time macros: $env, $asset, $nameof, $keys,
// $file, $git, and $buildTime. The compiler injects identical declarations
// in-memory, so this file exists purely for editors/IDEs (the scaffolded
// tsconfig lists it under "include"). See docs.md ("rotor extensions").
declare const $env: {
	readonly [envName: string]: string | undefined;
} & ((name: string, fallback: string) => string) &
	((name: string) => string | undefined);

declare function $asset(path: string): string;

declare function $nameof(item: unknown): string;
declare function $keys<T>(): string[];
declare function $file(path: string): any;
declare function $git(field: "sha" | "branch" | "tag"): string;
declare function $git(field: "dirty"): boolean;
declare function $buildTime(): string;
