// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	"key_icons/A": string
	"key_icons/B": string
	"key_icons/ButtonA": string
	"key_icons/ButtonB": string
	"key_icons/ButtonCircle": string
	"key_icons/ButtonCross": string
	"key_icons/ButtonSquare": string
	"key_icons/ButtonTriangle": string
	"key_icons/ButtonX": string
	"key_icons/ButtonY": string
	"key_icons/C": string
	"key_icons/D": string
	"key_icons/E": string
	"key_icons/F": string
	"key_icons/G": string
	"key_icons/H": string
	"key_icons/I": string
	"key_icons/J": string
	"key_icons/K": string
	"key_icons/L": string
	"key_icons/M": string
	"key_icons/N": string
	"key_icons/O": string
	"key_icons/P": string
	"key_icons/Q": string
	"key_icons/R": string
	"key_icons/S": string
	"key_icons/T": string
	"key_icons/U": string
	"key_icons/Unknown": string
	"key_icons/V": string
	"key_icons/W": string
	"key_icons/X": string
	"key_icons/Y": string
	"key_icons/Z": string
}

export = assets